### ISSUE TITLE
请教一下ndk如何配置？

### ISSUE THREAD

**Issue by Qdafengzi** [enbandari/Android-LuaJavax#2]

**Comment by bennyhuo** [comment]
不需要有特殊的配置，用as安装ndk会自动配置路径。

说一下你遇到的具体问题吧

**Comment by Qdafengzi** [comment]
> 不需要有特殊的配置，用as安装ndk会自动配置路径。
> 
> 说一下你遇到的具体问题吧

没事了，我导入的项目引入了MMKv库，只用了armeabi，我记忆中AndroidCPU架构中这个是应用最普遍的，还以为配置的ndk架构有问题，看了几篇文章才知道v7a才是主流。我配置的写法是没问题的。😀
